version: '3'

services:
  app:
    build: ./
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=dev
      - DB_URL=mongodb://mongo/th
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo
